#my:
#  app:
#    data:
#      S1: ENG
#      S2: HIN
#      S2: SCI
#    grades:
#      e1: A
#      e2: B
#      e3: A+

my:
  app:
    data:
      s1: ENG
      s2: MAT
      s3: SCI
    grades:
      e1: A
      e2: B
      e3: A+ 